# Generated by Django 2.0.6 on 2018-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_class',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='resume_class',
            name='phone',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='resume_class',
            name='whywehire_message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
