# Generated by Django 2.0.6 on 2018-06-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20180612_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=70)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
    ]
