# Generated by Django 2.0.6 on 2018-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_sessionclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionclass',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]
