# Generated by Django 2.0.6 on 2018-06-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_blogpostclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostclass',
            name='blogCoverImage',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='blogpostclass',
            name='blogImage',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
